### ISSUE TITLE
add support laravel 7

### ISSUE THREAD

**Issue by dswtech** [jalameta/jps-support#8]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for jalameta/jps-support ^0.1.12 -> satisfiable by jalameta/jps-support[v0.1.12].
    - Conclusion: remove ramsey/uuid 4.0.1
    - Conclusion: don't install ramsey/uuid 4.0.1
    - jalameta/jps-support v0.1.12 requires ramsey/uuid ^3.8 -> satisfiable by ramsey/uuid[3.8.0, 3.9.0, 3.9.1, 3.9.2, 3.9.3, 3.x-dev].
    - Can only install one of: ramsey/uuid[3.8.0, 4.0.1].
    - Can only install one of: ramsey/uuid[3.9.0, 4.0.1].
    - Can only install one of: ramsey/uuid[3.9.1, 4.0.1].
    - Can only install one of: ramsey/uuid[3.9.2, 4.0.1].
    - Can only install one of: ramsey/uuid[3.9.3, 4.0.1].
    - Can only install one of: ramsey/uuid[3.x-dev, 4.0.1].
    - Installation request for ramsey/uuid (locked at 4.0.1) -> satisfiable by ramsey/uuid[4.0.1].

**Comment by veelasky** [comment]
fixed in https://github.com/jalameta/jps-support/pull/9
